name: tests
on: [push, workflow_dispatch]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: lint
      - run: flutter analyze
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
      - name: test
      - run: flutter test
